name: tableau_langchain
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.12.2
    - conda-forge::notebook
    - conda-forge::nb_conda_kernels
    - ipykernel
    - python-dotenv
    - pyjwt
    - langchain
    - langsmith
    - pip=23.3.1
    - pip:
        - langgraph
        - langgraph-cli
        - langchain_anthropic
        - langchain_openai
        - langchain-pinecone
        - langchain-tableau
        - "langserve[all]"
        - langchain_community
        - langchain_experimental
        - llama-index
        - llama-index-vector-stores-pinecone
        - "pinecone-client[grpc]"
        - semantic-router
        - tavily-python
