name: tableau_langchain
channels:
    - conda-forge
    - defaults
dependencies:
    # 1. Define the base interpreter and core tools
    - python=3.12.2
    - pip>=23.3.1
    - conda-forge::notebook=7.3.3
    - conda-forge::nb_conda_kernels=2.5.1
    - ipykernel=6.29.5

    # 2. Tell pip to install your project and its dependencies
    #    from pyproject.toml
    - pip:
        - -e .
