[project]
name = "tableau_langchain"
version = "0.1.0"
description = "A community project to stage, test and build Tableau tools for Agents built with the Langgraph framework"
authors = [
    { name = "Stephen Price" },
    { name = "Joe Constantino" },
    { name = "Joseph Fluckiger" }
]
requires-python = ">=3.12.2"
license = "MIT"
readme = "README.md"

dependencies = [
    "python-dotenv",
    "langchain",
    "langgraph",
    "langsmith",
    "langchain-anthropic",
    "langchain-openai",
    "langchain-pinecone",
    "langchain-tableau",
    "langserve[all]",
    "langchain-community",
    "langchain-experimental",
    "llama-index",
    "llama-index-vector-stores-pinecone",
    "pinecone-client[grpc]",
    "semantic-router",
    "tavily-python"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["experimental"]
